### ISSUE TITLE
Add possibility to announce maintenance or news on main page

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/frontend#10]
Add functionality which will display information about planned maintenance at the top of the YANG Catalog.
Content of this message should be loaded from backend - new endpoint might be needed OR it can be fetched from some JSON file.
This component can be also used to display some news, like new release for example so different types of notifications can be displayed (info, warning).

**Comment by evyncke** [comment]
And don't forget to allow the removal of the news

**Comment by dmytro-kyrychenko** [comment]
Hi, @evyncke. 
![image](https://user-images.githubusercontent.com/112940673/211768387-da353c57-4c93-4331-b6ec-94e6c7eb6411.png)
Our current implementation for those notifications looks like this, and it shows on every page of the website. Which could be the problem, because even after dismissing it on previous page, you will get the same notification on the next page. We could solve this by using cookies on website, but we don't use them currently, so this will make things much more complicated. Alternative approach, we can show this maintenance message only on [home page](https://yangcatalog.org/) (for each reload notification will be shown again, but only for home.html)

So, what do you think? Should we stick to showing it only on home?

**Comment by dmytro-kyrychenko** [comment]
Hi, @evyncke. So what do you think about my previous comment?
